import type { Metadata } from "next";

import { Reem_Kufi_Ink, Days_One, Anek_Malayalam } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const reemKufiInk = Reem_Kufi_Ink({
  variable: "--font-reem-kufi-ink",
  subsets: ["latin"],
  weight: "400",
});

const daysOne = Days_One({
  variable: "--font-days-one",
  subsets: ["latin"],
  weight: "400",
});

const anekMalayalam = Anek_Malayalam({
  variable: "--font-anek-malayalam",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/prism-themes@1.9.0/themes/prism-one-light.css"
        />
      </head>
      <body
        className={`${reemKufiInk.variable} ${daysOne.variable} ${anekMalayalam.variable} antialiased`}
      >
        <Navbar />

        {children}
      </body>
    </html>
  );
}
